### PR TITLE
Bump mxnet versions tested on CI

### PR DESCRIPTION
**Pull request by leezu**
Check if pointwise fusion failure is present on bumped version

See https://github.com/dmlc/gluon-nlp/pull/1230#issuecomment-698028126

cc @ptrendx

### CODE REVIEW

**Comment by leezu** [comment]
cc @MoisesHer does the bertpass_gpu.cc need any update to work with MXNet 1.8 / 1.x branch?

**Comment by leezu** [comment]
Blocked by  

```
Reshape_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_expand_dims_kernel.cu(1084): Error: Formal parameter space overflowed (4648 bytes required, max 4096 bytes allowed) in function
```

**Comment by MoisesHer** [comment]
> cc @MoisesHer does the bertpass_gpu.cc need any update to work with MXNet 1.8 / 1.x branch?

I have tested, and I am having issues to compile with MXNet v1.8.x:

```
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:59:25: error: ‘JsonVal’ has not been declared
   static Graph fromJson(JsonVal val) {
                         ^~~~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:120:3: error: ‘JsonVal’ does not name a type
   JsonVal toJson() {
   ^~~~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:247:25: error: ‘JsonVal’ was not declared in this scope
   std::map<std::string, JsonVal> attrs;
                         ^~~~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:247:25: note: suggested alternative:
In file included from /moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:31:0:
/moisesh-data/PRs_mxnet/test_MXNET1.8/incubator-mxnet/include/mxnet/lib_api.h:499:8: note:   ‘mxnet::ext::JsonVal’
 struct JsonVal {
        ^~~~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:247:32: error: template argument 2 is invalid
   std::map<std::string, JsonVal> attrs;
                                ^
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:247:32: error: template argument 4 is invalid
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc: In static member function ‘static Graph Graph::fromString(const string&)’:
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:51:5: error: ‘JsonParser’ was not declared in this scope
     JsonParser parser;
     ^~~~~~~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:52:5: error: ‘JsonVal’ was not declared in this scope
     JsonVal val = parser.parse_to_json(json);
     ^~~~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:52:5: note: suggested alternative:
In file included from /moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:31:0:
/moisesh-data/PRs_mxnet/test_MXNET1.8/incubator-mxnet/include/mxnet/lib_api.h:499:8: note:   ‘mxnet::ext::JsonVal’
 struct JsonVal {
        ^~~~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:53:21: error: ‘val’ was not declared in this scope
     return fromJson(val);
                     ^~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc: In static member function ‘static Graph Graph::fromJson(int)’:
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:61:5: error: ‘JsonVal’ was not declared in this scope
     JsonVal nodes = val.map[JsonVal("nodes")];
     ^~~~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:61:5: note: suggested alternative:
In file included from /moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:31:0:
/moisesh-data/PRs_mxnet/test_MXNET1.8/incubator-mxnet/include/mxnet/lib_api.h:499:8: note:   ‘mxnet::ext::JsonVal’
 struct JsonVal {
        ^~~~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:66:20: error: invalid use of member ‘Graph::nodes’ in static member function
     for(int i=0; i<nodes.list.size(); i++) {
                    ^~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:244:22: note: declared here
   std::vector<Node*> nodes;
                      ^~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:69:15: error: expected ‘;’ before ‘node’
       JsonVal node = nodes.list[i];
               ^~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:72:15: error: ‘node’ was not declared in this scope
       n->op = node.map[JsonVal("op")].str;
               ^~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:72:15: note: suggested alternative: ‘nodes’
       n->op = node.map[JsonVal("op")].str;
               ^~~~
               nodes
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:80:15: error: expected ‘;’ before ‘attributes’
       JsonVal attributes = node.map[JsonVal("attrs")];
               ^~~~~~~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:81:22: error: ‘attributes’ was not declared in this scope
       for(auto& kv : attributes.map) {
                      ^~~~~~~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:81:22: note: suggested alternative: ‘__attribute__’
       for(auto& kv : attributes.map) {
                      ^~~~~~~~~~
                      __attribute__
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:86:15: error: expected ‘;’ before ‘node_inputs’
       JsonVal node_inputs = node.map[JsonVal("inputs")];
               ^~~~~~~~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:87:24: error: ‘node_inputs’ was not declared in this scope
       n->inputs.resize(node_inputs.list.size());
                        ^~~~~~~~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:87:24: note: suggested alternative: ‘inputs’
       n->inputs.resize(node_inputs.list.size());
                        ^~~~~~~~~~~
                        inputs
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:89:17: error: expected ‘;’ before ‘input’
         JsonVal input = node_inputs.list[j];
                 ^~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:92:30: error: ‘input’ was not declared in this scope
         entry.node = nodeMap[input.list[0].num];
                              ^~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:92:30: note: suggested alternative: ‘inputs’
         entry.node = nodeMap[input.list[0].num];
                              ^~~~~
                              inputs
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:101:14: error: ‘heads’ was not declared in this scope
     JsonVal& heads = val.map[JsonVal("heads")];
              ^~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:101:26: error: request for member ‘map’ in ‘val’, which is of non-class type ‘int’
     JsonVal& heads = val.map[JsonVal("heads")];
                          ^~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:104:15: error: expected ‘;’ before ‘head’
       JsonVal head = heads.list[i];
               ^~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:105:35: error: ‘head’ was not declared in this scope
       g.outputs[i].node = nodeMap[head.list[0].num];
                                   ^~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:105:35: note: suggested alternative: ‘fread’
       g.outputs[i].node = nodeMap[head.list[0].num];
                                   ^~~~
                                   fread
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:109:5: error: ‘JsonParser’ was not declared in this scope
     JsonParser parser;
     ^~~~~~~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:110:24: error: request for member ‘map’ in ‘val’, which is of non-class type ‘int’
     for(auto& kv : val.map) {
                        ^~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc: In member function ‘std::__cxx11::string Graph::toString()’:
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:182:5: error: ‘JsonParser’ was not declared in this scope
     JsonParser parser;
     ^~~~~~~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:183:12: error: ‘parser’ was not declared in this scope
     return parser.dump(toJson());
            ^~~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:183:12: note: suggested alternative: ‘strsep’
     return parser.dump(toJson());
            ^~~~~~
            strsep
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:183:24: error: ‘toJson’ was not declared in this scope
     return parser.dump(toJson());
                        ^~~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:183:24: note: suggested alternative: ‘fromJson’
     return parser.dump(toJson());
                        ^~~~~~
                        fromJson
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc: At global scope:
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:251:1: error: ‘MXReturnValue’ does not name a type
 MXReturnValue custom_pass(const std::string& in_graph, const std::string** out_graph,
 ^~~~~~~~~~~~~
In file included from /moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:31:0:
/moisesh-data/PRs_mxnet/test_MXNET1.8/incubator-mxnet/include/mxnet/lib_api.h:921:37: error: ‘CustomPass’ does not name a type; did you mean ‘wcstombs’?
 #define MX_REGISTER_PASS_DEF_(Name) CustomPass MX_REGISTER_PASS_NAME_(Name)
                                     ^
/moisesh-data/PRs_mxnet/test_MXNET1.8/incubator-mxnet/include/mxnet/lib_api.h:906:34: note: in definition of macro ‘MX_STR_CONCAT_’
 #define MX_STR_CONCAT_(__a, __b) __a ## __b
                                  ^~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/incubator-mxnet/include/mxnet/lib_api.h:932:3: note: in expansion of macro ‘MX_STR_CONCAT’
   MX_STR_CONCAT(MX_REGISTER_PASS_DEF_(Name), __COUNTER__) = \
   ^~~~~~~~~~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/incubator-mxnet/include/mxnet/lib_api.h:932:17: note: in expansion of macro ‘MX_REGISTER_PASS_DEF_’
   MX_STR_CONCAT(MX_REGISTER_PASS_DEF_(Name), __COUNTER__) = \
                 ^~~~~~~~~~~~~~~~~~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:439:1: note: in expansion of macro ‘REGISTER_PASS’
 REGISTER_PASS(custom_pass)
 ^~~~~~~~~~~~~
/moisesh-data/PRs_mxnet/test_MXNET1.8/gluon-nlp/scripts/bert/bertpass_gpu.cc:442:1: error: ‘MXReturnValue’ does not name a type
 MXReturnValue initialize(int version) {
 ^~~~~~~~~~~~~

```

@samskalicky, Do we need to make changes on GluonNLP?

**Comment by samskalicky** [comment]
@MoisesHer https://github.com/dmlc/gluon-nlp/issues/1388 Check this out
