### PR TITLE
fix _fork attr in sharded_dataloader

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
## Description ##
@zhreshold @szhengac @leezu @szha 
Fix error: 
`AttributeError: 'list' object has no attribute '_fork'`
similar to https://github.com/apache/incubator-mxnet/pull/12093/files 

So that v0.4.1 can depend on mxnet 1.3.0

### Essentials ###
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by zhreshold** [comment]
@eric-haibin-lin Is this duplicate of https://github.com/dmlc/gluon-nlp/pull/353 ?

**Comment by eric-haibin-lin** [comment]
@zhreshold  Does 353 depends on mxnet master instead of 1.3.0?

**Comment by szha** [comment]
@zhreshold this is intentional in that #353 depends on at least 1.3.1, while we still want gluonnlp 0.4.1 to depend on 1.3.0. Once we finish the release of 0.4.1 we will merge #353

**Comment by zhreshold** [comment]
@eric-haibin-lin @szha No, https://github.com/dmlc/gluon-nlp/pull/353 I have striped dependency for 1.3.1, it should work on 1.3.0

**Comment by eric-haibin-lin** [comment]
I had misunderstanding. closing it now
